services:
  - name: soap-alumno
    type: web
    runtime: java
    buildCommand: cd SOAP-Alumno && mvn clean package -DskipTests
    startCommand: java -jar SOAP-Alumno/target/*.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://academico.cz4y4e0k6dqi.us-east-2.rds.amazonaws.com:3306/soap_proyecto?useSSL=false&serverTimezone=UTC
      - key: SPRING_DATASOURCE_USERNAME
        value: admin
      - key: SPRING_DATASOURCE_PASSWORD
        value: dbacademico
      - key: SERVER_PORT
        value: 10000

  - name: soap-asistencia
    type: web
    runtime: java
    buildCommand: cd SOAP-Asistencia && mvn clean package -DskipTests
    startCommand: java -jar SOAP-Asistencia/target/*.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://academico.cz4y4e0k6dqi.us-east-2.rds.amazonaws.com:3306/soap_proyecto?useSSL=false&serverTimezone=UTC
      - key: SPRING_DATASOURCE_USERNAME
        value: admin
      - key: SPRING_DATASOURCE_PASSWORD
        value: dbacademico
      - key: SERVER_PORT
        value: 10000

  - name: soap-curso
    type: web
    runtime: java
    buildCommand: cd SOAP-Curso && mvn clean package -DskipTests
    startCommand: java -jar SOAP-Curso/target/*.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://academico.cz4y4e0k6dqi.us-east-2.rds.amazonaws.com:3306/soap_proyecto?useSSL=false&serverTimezone=UTC
      - key: SPRING_DATASOURCE_USERNAME
        value: admin
      - key: SPRING_DATASOURCE_PASSWORD
        value: dbacademico
      - key: SERVER_PORT
        value: 10000

  - name: soap-docente
    type: web
    runtime: java
    buildCommand: cd SOAP-Docente && mvn clean package -DskipTests
    startCommand: java -jar SOAP-Docente/target/*.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://academico.cz4y4e0k6dqi.us-east-2.rds.amazonaws.com:3306/soap_proyecto?useSSL=false&serverTimezone=UTC
      - key: SPRING_DATASOURCE_USERNAME
        value: admin
      - key: SPRING_DATASOURCE_PASSWORD
        value: dbacademico
      - key: SERVER_PORT
        value: 10000

  - name: soap-matricula
    type: web
    runtime: java
    buildCommand: cd SOAP-Matricula && mvn clean package -DskipTests
    startCommand: java -jar SOAP-Matricula/target/*.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://academico.cz4y4e0k6dqi.us-east-2.rds.amazonaws.com:3306/soap_proyecto?useSSL=false&serverTimezone=UTC
      - key: SPRING_DATASOURCE_USERNAME
        value: admin
      - key: SPRING_DATASOURCE_PASSWORD
        value: dbacademico
      - key: SERVER_PORT
        value: 10000

  - name: soap-nota
    type: web
    runtime: java
    buildCommand: cd SOAP-Nota && mvn clean package -DskipTests
    startCommand: java -jar SOAP-Nota/target/*.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://academico.cz4y4e0k6dqi.us-east-2.rds.amazonaws.com:3306/soap_proyecto?useSSL=false&serverTimezone=UTC
      - key: SPRING_DATASOURCE_USERNAME
        value: admin
      - key: SPRING_DATASOURCE_PASSWORD
        value: dbacademico
      - key: SERVER_PORT
        value: 10000

  - name: soap-cuenta
    type: web
    runtime: java
    buildCommand: cd SOAP-Cuenta && mvn clean package -DskipTests
    startCommand: java -jar SOAP-Cuenta/target/*.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://academico.cz4y4e0k6dqi.us-east-2.rds.amazonaws.com:3306/soap_proyecto?useSSL=false&serverTimezone=UTC
      - key: SPRING_DATASOURCE_USERNAME
        value: admin
      - key: SPRING_DATASOURCE_PASSWORD
        value: dbacademico
      - key: SERVER_PORT
        value: 10000

  - name: frontend-academico
    type: web
    runtime: java
    buildCommand: cd Frontend-Academico && mvn clean package -DskipTests
    startCommand: java -jar Frontend-Academico/target/*.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://academico.cz4y4e0k6dqi.us-east-2.rds.amazonaws.com:3306/soap_proyecto?useSSL=false&serverTimezone=UTC
      - key: SPRING_DATASOURCE_USERNAME
        value: admin
      - key: SPRING_DATASOURCE_PASSWORD
        value: dbacademico
      - key: SERVER_PORT
        value: 10000