services:
  - name: soap-alumno
    type: web
    runtime: docker
    dockerfilePath: ./SOAP-Alumno/Dockerfile
    dockerContext: ./SOAP-Alumno
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://academico.cz4y4e0k6dqi.us-east-2.rds.amazonaws.com:3306/soap_proyecto?useSSL=false&serverTimezone=UTC
      - key: SPRING_DATASOURCE_USERNAME
        value: admin
      - key: SPRING_DATASOURCE_PASSWORD
        value: dbacademico

  - name: soap-asistencia
    type: web
    runtime: docker
    dockerfilePath: ./SOAP-Asistencia/Dockerfile
    dockerContext: ./SOAP-Asistencia
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://academico.cz4y4e0k6dqi.us-east-2.rds.amazonaws.com:3306/soap_proyecto?useSSL=false&serverTimezone=UTC
      - key: SPRING_DATASOURCE_USERNAME
        value: admin
      - key: SPRING_DATASOURCE_PASSWORD
        value: dbacademico

  - name: soap-curso
    type: web
    runtime: docker
    dockerfilePath: ./SOAP-Curso/Dockerfile
    dockerContext: ./SOAP-Curso
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://academico.cz4y4e0k6dqi.us-east-2.rds.amazonaws.com:3306/soap_proyecto?useSSL=false&serverTimezone=UTC
      - key: SPRING_DATASOURCE_USERNAME
        value: admin
      - key: SPRING_DATASOURCE_PASSWORD
        value: dbacademico

  - name: soap-docente
    type: web
    runtime: docker
    dockerfilePath: ./SOAP-Docente/Dockerfile
    dockerContext: ./SOAP-Docente
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://academico.cz4y4e0k6dqi.us-east-2.rds.amazonaws.com:3306/soap_proyecto?useSSL=false&serverTimezone=UTC
      - key: SPRING_DATASOURCE_USERNAME
        value: admin
      - key: SPRING_DATASOURCE_PASSWORD
        value: dbacademico

  - name: soap-matricula
    type: web
    runtime: docker
    dockerfilePath: ./SOAP-Matricula/Dockerfile
    dockerContext: ./SOAP-Matricula
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://academico.cz4y4e0k6dqi.us-east-2.rds.amazonaws.com:3306/soap_proyecto?useSSL=false&serverTimezone=UTC
      - key: SPRING_DATASOURCE_USERNAME
        value: admin
      - key: SPRING_DATASOURCE_PASSWORD
        value: dbacademico

  - name: soap-nota
    type: web
    runtime: docker
    dockerfilePath: ./SOAP-Nota/Dockerfile
    dockerContext: ./SOAP-Nota
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://academico.cz4y4e0k6dqi.us-east-2.rds.amazonaws.com:3306/soap_proyecto?useSSL=false&serverTimezone=UTC
      - key: SPRING_DATASOURCE_USERNAME
        value: admin
      - key: SPRING_DATASOURCE_PASSWORD
        value: dbacademico

  - name: soap-cuenta
    type: web
    runtime: docker
    dockerfilePath: ./SOAP-Cuenta/Dockerfile
    dockerContext: ./SOAP-Cuenta
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://academico.cz4y4e0k6dqi.us-east-2.rds.amazonaws.com:3306/soap_proyecto?useSSL=false&serverTimezone=UTC
      - key: SPRING_DATASOURCE_USERNAME
        value: admin
      - key: SPRING_DATASOURCE_PASSWORD
        value: dbacademico

  - name: frontend-academico
    type: web
    runtime: docker
    dockerfilePath: ./Frontend-Academico/Dockerfile
    dockerContext: ./Frontend-Academico
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://academico.cz4y4e0k6dqi.us-east-2.rds.amazonaws.com:3306/soap_proyecto?useSSL=false&serverTimezone=UTC
      - key: SPRING_DATASOURCE_USERNAME
        value: admin
      - key: SPRING_DATASOURCE_PASSWORD
        value: dbacademico
